### ISSUE TITLE
Falta documentación for dummies

### ISSUE THREAD

**Issue by iorch** [mxabierto/validadora#24]
+ Intenté el procedimiento con Docker, pero al parecer hay un problema con el server. 
```
Sending build context to Docker daemon 14.07 MB
Step 1 : FROM alpine:latest
Pulling repository docker.io/library/alpine
Error while pulling image: Get https://index.docker.io/v1/repositories/library/alpine/images: dial tcp: lookup index.docker.io on 189.209.208.181:53: server misbehaving
```

+ Mientras se corrige el problema, intenté seguir el método de python. Al parecer se hico la instalación de los requirements correctamente, y también el setup. Sin embargo al correr run.py obtuve el siguiente traceback

```
Traceback (most recent call last):
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/docker/unixconn/unixconn.py", line 41, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/docker/unixconn/unixconn.py", line 41, in connect
    sock.connect(self.unix_socket)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/run.py", line 2, in <module>
    from validadora import run
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/validadora/__init__.py", line 10, in <module>
    from . import views
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/validadora/views.py", line 9, in <module>
    validators = _M.repo.list_validadores()
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/validadora/manager/repositorio.py", line 30, in list_validadores
    validadores = [ Validador(image, repo=self) for image in self.client.images()
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/docker/client.py", line 374, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/iorch/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by rodowi** [comment]
@iorch ese "server misbehaving" parece que es al intentar bajar imagen. Intenta de nuevo y dinos si sigue pasando.

**Comment by iorch** [comment]
@rodowi: sí se arregló después el error del servidor. Mi sugerencia es mejorar la documentación para quien quiera usar la validadora como un script de python.
