### ISSUE TITLE
Siguiendo las instrucciones de la Wiki, run.py falla por falta de módulo Flask

### ISSUE THREAD

**Issue by rodowi** [mxabierto/validadora#3]
(validadora)➜  validadora git:(develop) ✗ python bin/run.py      
Traceback (most recent call last):
  File "bin/run.py", line 2, in <module>
    from validadora import run
  File "/Users/rodolfo/.virtualenvs/validadora/lib/python2.7/site-packages/validadora/__init__.py", line 1, in <module>
    from flask import Flask
ImportError: No module named flask

**Comment by zoek1** [comment]
@rodowi se agrego la documentación del manejo de dependencias de la validadora en la [4ta revisión](https://github.com/mxabierto/validadora/wiki/Home/b30befffe5ef85138a7b902413567ca38d129bb6).

La origen del error se debe a que no se ejecuta `pip` antes de instalar el paquete de la validadora o de su ejecución.

**Comment by rodowi** [comment]
```bash
(validadora)➜  validadora git:(develop) ✗ python bin/run.py 
Traceback (most recent call last):
  File "bin/run.py", line 2, in <module>
    from validadora import run
  File "/Users/rodolfo/.virtualenvs/validadora/lib/python2.7/site-packages/validadora/__init__.py", line 10, in <module>
    from . import views
  File "/Users/rodolfo/.virtualenvs/validadora/lib/python2.7/site-packages/validadora/views.py", line 4, in <module>
    from validadora.manager.manager import Manager
  File "/Users/rodolfo/.virtualenvs/validadora/lib/python2.7/site-packages/validadora/manager/manager.py", line 7, in <module>
    from queue import Queue
ImportError: No module named queue
```

**Comment by zoek1** [comment]
Necesita la versión 3 o superior de Python para ejecutarse. El modulo queue fue agregado en dicha versión.
