### ISSUE TITLE
Siguiendo la Wiki, falla el docker-container run

### ISSUE THREAD

**Issue by rodowi** [mxabierto/validadora#4]
Parece que tenemos que levantar un container de mongodb también:

```bash
bash-3.2$ docker run -v /tmp:/datasets -p 5000:5000 mxabierto/validadora
Traceback (most recent call last):
  File "bin/run.py", line 2, in <module>
    from validadora import run
  File "/usr/lib/python3.4/site-packages/validadora/__init__.py", line 10, in <module>
    from . import views
  File "/usr/lib/python3.4/site-packages/validadora/views.py", line 8, in <module>
    _M = Manager()
  File "/usr/lib/python3.4/site-packages/validadora/manager/manager.py", line 26, in __init__
    self.db = MongoClient(os.environ['MONGO_PORT_27017_TCP_ADDR'], int(os.environ["MONGO_PORT_27017_TCP_PORT"]))
  File "/usr/lib/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'MONGO_PORT_27017_TCP_ADDR'
```

**Comment by rodowi** [comment]
Se resuelve, levantando instancia de mongo

```bash
bash-3.2$ docker run --name validadora-mongo -d mongo
```
Y linkeando
```
bash-3.2$ docker run --link validadora-mongo:mongo -v /tmp:/datasets -p 5000:5000 mxabierto/validadora
```

**Comment by rodowi** [comment]
Ahora se queja de "FileNotFound"

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/docker/unixconn/unixconn.py", line 41, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/docker/unixconn/unixconn.py", line 41, in connect
    sock.connect(self.unix_socket)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/run.py", line 2, in <module>
    from validadora import run
  File "/usr/lib/python3.4/site-packages/validadora/__init__.py", line 10, in <module>
    from . import views
  File "/usr/lib/python3.4/site-packages/validadora/views.py", line 9, in <module>
    validators = _M.repo.list_validadores()
  File "/usr/lib/python3.4/site-packages/validadora/manager/repositorio.py", line 30, in list_validadores
    validadores = [ Validador(image, repo=self) for image in self.client.images()
  File "/usr/lib/python3.4/site-packages/docker/client.py", line 374, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/usr/lib/python3.4/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
bash-3.2$ 

```

**Comment by zoek1** [comment]
@rodowi agregaremos el requerimiento de la base de datos para complementar la documentación.
El segundo error es causado por que el cliente de docker y el socket se encuentran separados o no son accesibles. Una solución es hacer binding del socket al contenedor de la validora:

```console
 docker run --link validadora-mongo:mongo -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/datasets -p 5000:5000 mxabierto/validadora
```

La segunda seria pasar la IP y el puerto a conectar. Esta opción permitiría incluso trabajar con un cluster o boot2docker en el caso de Mac y Windows (requiere implementarse).

**Comment by zoek1** [comment]
Se agrego documentación para configuración y los elementos requeridos para el contenedor de la validadora en el [5ta revision](https://github.com/mxabierto/validadora/wiki/Home/dbadb65034901a0eead929617cd6f4fe8192b3e5) de la wiki.

**Comment by rodowi** [comment]
Con esa documentación, me funcionó perfecto.
